### ISSUE TITLE
A couple of suggestions

### ISSUE THREAD

**Issue by neatdot** [toowaki/AutoFitRowEx#1]
This is brilliant - many thanks for creating such a great tool!

A couple of suggestions:

1. Generate a completely random sheet name for the temporary sheet to avoid any clashes with existing sheet names (unlikely, I know...)
2. Turn off screen updates to prevent screen flicker during the creation and deletion of the temporary sheet
3. An option that allows a default behaviour to be set, so that the auto-row height will run without any dialogs

**Comment by toowaki** [comment]
Thank you for your message.
A1:
I don't think user will have the same name. But, thank you for your advice.
A2:
When I stopped updating the screen in Excel 2013 or later, the processing became very slow, so I turned on screen updating.
A3:
I will try to implement the proposal in Q3.

**Comment by toowaki** [comment]
Hello Steve James,
I added the following two shortcuts.
- [No dialog and execute for display] Ctrl + Shift + t
- [No dialog and execute for print] Ctrl + Shift + y

Please try to use V2.7. 
https://github.com/toowaki/AutoFitRowEx/releases/tag/V2.7

**Comment by toowaki** [comment]
Thank you for your advice.
I'll close this issue.
